// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgy62viYoH4TRvQiPJ0Y9izyMn_Rsi24',
    appId: '1:10655515722:web:f8429bfd4f1e6c82f8d2b3',
    messagingSenderId: '10655515722',
    projectId: 'my-fan-page-app',
    authDomain: 'my-fan-page-app.firebaseapp.com',
    storageBucket: 'my-fan-page-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKlkgY7HfGGmtcgJTk6cK29k-9fpfX10I',
    appId: '1:10655515722:android:95be31b09c730047f8d2b3',
    messagingSenderId: '10655515722',
    projectId: 'my-fan-page-app',
    storageBucket: 'my-fan-page-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-tcs0vzdelKiaSTdT4B9gmIZKtmzjV0',
    appId: '1:10655515722:ios:93916dfb51279a6ff8d2b3',
    messagingSenderId: '10655515722',
    projectId: 'my-fan-page-app',
    storageBucket: 'my-fan-page-app.appspot.com',
    iosClientId: '10655515722-cuqhllf5lm4r8bor1jhoroi8imj7sq91.apps.googleusercontent.com',
    iosBundleId: 'com.fanpage.my.myfanpage',
  );
}
